const Data = {
  En: [
    "<html><head><style type='text/css'> @font-face {font-family: 'customFont'; src:url('../../../assets/fonts/Archer-Medium-Pro.ttf')} body{font-family:'customFont'}</style><meta name='viewport' content='width=device-width, initial-scale=1.0'></head><body><p>QFB Digital Banking Application is only intended for &ldquo;Qualified Investors&rdquo;. By using this Application, you acknowledge at your own risk that you fulfill the eligibility criteria for Qualified Investors as defined under these Terms and Conditions and as set out under the QFC Regulations as amended from time to time.</p> <p>The &ldquo;Qualified Investor&rdquo; was defined as follows:</p> <p><span >Qualified Investor:</span> refers to the natural persons and entities that meet the requirements stated in the definition above who shall be considered eligible for to subscribe for the QFB products and services.</p> <p><span >Eligibility Criteria:</span></p> <ol> <li><span >Natural Persons: </span> <ul> <li>Shall have a minimum net worth of four (4) million QAR, excluding the calculation of the value of the primary residence of the Qualified Investor.</li> </ul> </li> <li><span >Corporate Entities:</span> <ul> <li><span >a body corporate that has (or, at any time during the previous 2 years, has had) either: </span> <ul> <li>called-up share capital, or net assets, of QR 18 million or more; or</li> <li>annual net turnover of QR 30 million or more;</li> </ul> </li> <li><span >a body corporate that has a holding company or subsidiary that has (or, at any time during the previous 2 years, has had) either:</span> <ul> <li>called-up share capital, or net assets, of at least QR 18 million; or</li> <li>annual net turnover of QR 30 million or more;</li> </ul> </li> <li><span >a partnership or unincorporated association that has (or, at any time during the previous 2 years, has had) either:</span> <ul> <li>net assets of QR 18 million or more (calculated, in the case of a limited partnership, without deducting loans owing to any of the partners); or</li> <li>annual net turnover of QR 30 million or more.</li> </ul> </li> </ul> </li> <li><span >Eligible Counterparty: </span> <ul> <li>an authorized firm;</li> <li>a regulated financial institution;</li> <li>an eligible clearing house or eligible exchange;</li> <li>a government, government agency, or central bank or other national monetary authority, of any jurisdiction;</li> <li>a state investment body, or a body charged with, or intervening in, the management of the public debt;</li> <li>a supranational organization, the members of which are jurisdictions, central banks or national monetary authorities.</li> </ul> </li> </ol></body></html>",
  ],
  Ar: [
    "<p>تطبيق خدمات بنك قطر الأول الإلكترونية هو تطبيق موجه فقط لاستخدام 'المستثمر المؤهل'. من خلال استعمال هذا التطبيق يقر العميل على مسؤوليته الخاصة بأنه يستوفي جميع معايير التأهل 'للمستثمر المؤهل' كما ورد تعريفه في هذه الأحكام والشروط، وفي قوانين مركز قطر للمال بصيغتها المعدلة من وقت لآخر.</p> <p>&nbsp;وقد تم تعريف المستثمر المؤهل كالتالي:</p> <p><span>المستثمر المؤهل: </span>وتعود على الأشخاص الطبيعيين أو القانونيين الذين يستوفون المعايير المنصوص عليها في التعريف التالي، ويعد هؤلاء مؤهلون للاشتراك في خدمات ومنتجات بنك قطر الأول.</p> <p><span>معايير التأهل:</span></p> <ol> <li><span>شخص طبيعي: </span></li> </ol> <p>&middot; أن يبلغ صافي قيمة ثروته أربعة (4) مليون ريال قطري على الأقل ويستثنى من هذا المبلغ قيمة مسكن المستثمر المؤهل (مكان إقامته) الأساسي.</p> <ol start='3'> <li ><span>شركة:</span></li> </ol> <ul> <li ><span>أن تكون الشركة قد (أو خلال السنتين الماضيتين قد) إما: </span></li> </ul> <p>&middot; أن يقدر رأسمالها السهمي أو صافي قيمة أصولها بثمانية عشر (18) مليون ريال قطري أو أكثر، أو</p> <p>&middot; أن تقدر قيمة صافي حجم أعمالها السنوي بثلاثين (30) مليون ريال قطري أو أكثر.</p> <ul> <li><span>أن تمتلك الشركة المستثمرة شركة قابضة أو شركة تابعة لها تكون قد (أو خلال السنتين الماضيتين قد) إما: </span></li> </ul> <p>&middot; أن يقدر رأسمالها أو صافي قيمة أصولها بثمانية عشر (18) مليون ريال قطري على الأقل، أو</p> <p>&middot; أن تقدر قيمة صافي حجم أعمالها السنوي بثلاثين (30) مليون ريال قطري أو أكثر.</p> <ul> <li><span>الشراكات والشركات الفردية غير المسجلة التي تكون قد (أو خلال السنتين السابقتين، قد) إما:</span></li> </ul> <p>&middot; أن تقدر قيمة صافي أصولها بثمانية عشر (18) مليون ريال قطري أو أكثر (ولا يستثنى من هذه القيمة احتساب القروض التي ضخها أي من الشركاء في رأسمال الشراكات المحدودة) أو</p> <p>&middot; أن تكون قيمة صافي حجم الأعمال ثلاثين (30) مليون ريال قطري أو أكثر.</p> <ol start='3'> <li ><span>الطرف المقابل المؤهل: </span></li> </ol> <ul> <li>أن تكون شركة مرخصة من قبل مركز قطر للمال.</li> <li>مؤسسة مالية مرخصة حسب الأصول.</li> <li>مركز مقاصة مؤهل أو بورصة مؤهلة.</li> </ul> <ul> <li>حكومة أو وكالة حكومية أو بنك مركزي أو غيرها من الهيئات النقدية الوطنية في أي دولة.</li> </ul> <ul> <li>هيئة استثمارية تابعة للدولة، أو أي هيئة مسؤولة عن أو تتدخل في إدارة المديونية العامة.</li> </ul> <ul> <li>منظمة إقليمية أو دولية يكون أعضاءها إما دول أو بنوك مركزية أو هيئات نقدية وطنية.</li> </ul>",
  ],
};

export default {
  Data,
};
