export default {
  IdentityBaseUrl: "https://identity-stg.azurewebsites.net",
  ApiBaseUrl: "https://api-stg.azurewebsites.net",
  AnonymousTermsAcceptanceStorageKey: "@storage_AcceptTermsStatusForAnonymous1",
  CustomerTermsAcceptanceStorageKey: "@storage_AcceptTermsStatusForCustomer",
  LoginDetailsStorageKey: "storage_LoginUsernameAndPassword",
  UserProfileDetailsStorageKey: "storage_UserPofileDetails",
  RecordPerPage: 5,
  AccessTokenStorageKey: "storage_user_access_token",
  RefreshTokenStorageKey: "storage_user_refresh_token",
  SpinnerColor: "#6B4F44",
  SpnnerSize: 140,
  Customer: "CUSTOMER",
  Management: "MANAGEMENT",
  RM: "RM",
  AlertTimeout: 3000,
};
