export default { 
  IdentityBaseUrl: "https://identitydev.qfbonline.com",
  ApiBaseUrl: "https://apidev.qfbonline.com",
  PortalUrl: "https://ibdev.qfbonline.com.com",
  AnonymousTermsAcceptanceStorageKey: "@storage_AcceptTermsStatusForAnonymous1",
  CustomerTermsAcceptanceStorageKey: "@storage_AcceptTermsStatusForCustomer",
  LoginDetailsStorageKey: "storage_LoginUsernameAndPassword",
  UserProfileDetailsStorageKey: "storage_UserPofileDetails",
  RecordPerPage: 5,
  AccessTokenStorageKey: "storage_user_access_token",
  RefreshTokenStorageKey: "storage_user_refresh_token",
  SpinnerColor: "#6B4F44",
  SpnnerSize: 140,
  Customer: "CUSTOMER",
  Management: "MANAGEMENT",
  RM: "RM",
  CMSADMIN: "CMSADMIN",
  AlertTimeout: 3000,
  MapApiKey: "AIzaSyChFfCU3MWxnnsh79D5Lf6_YYiEahZMvcQ",
};
